---
title: "Process NHRSA Html To Linked"
author: "K Belisle"
date: "March 4, 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors = F)

```

```{r tidyverse-stuff}
library(xml2)
library(dplyr)
library(purrr)
library(stringr)

# From the root node:
# If has_children, then recurse.
# Otherwise, attributes, value and children (nested) to data frame.

xml_to_df <- function(doc, ns = xml_ns(doc)) {
  node_to_df <- function(node) {
    # Filter the attributes for ones that aren't namespaces
    # x <- list(.index = 0, .name = xml_name(node, ns))
    x <- list(.name = xml_name(node, ns))
    # Attributes as column headers, and their values in the first row
    attrs <- xml_attrs(node)
    if (length(attrs) > 0) {attrs <- attrs[!grepl("xmlns", names(attrs))]}
    if (length(attrs) > 0) {x <- c(x, attrs)}
    # Build data frame manually, to avoid as.data.frame's good intentions
    children <- xml_children(node)
    if (length(children) >= 1) {
      x <- 
        children %>%
        # Recurse here
        map(node_to_df) %>%
        split_by(".name") %>%
        map(bind_rows) %>%
        map(list) %>%
        {c(x, .)}
      attr(x, "row.names") <- 1L
      class(x) <- c("tbl_df", "data.frame")
    } else {
      x$.value <- xml_text(node)
    }
    x
  }
  node_to_df(doc)
}

```


```{r read-html-files}
require(data.table)
rsahtml<-list.files(path="../html/",pattern="*.htm",recursive = T,full.names = T)
rsahtml<-rsahtml[!(rsahtml %like% "mrg")]
head(rsahtml)
```
rsaxml:
titlename
chapter
subchapter
sectionnumber
sectiontitle
codesec
sourcenote
```{r set-literals}
bodytags=c("h1","h2","h3","b","codesect","sourcenote")
bodytags7=c("h1","h2","h2","h3","b","codesect","sourcenote")
dftags=c("title","chapter","sectionnum","sectiontitle","codesec","sourcenote")
dftags7=c("title","chapter","subchapter","sectionnum","sectiontitle","codesec","sourcenote")
dftags8=c("title","chapter","sectionnum","enactnote","repealnotes","sectiontitle","codesec","sourcenote")
dftags9=c("title","chapter","subchapter","sectionnum","enactlnote","repealnotes","sectiontitle","codesec","sourcenote")
dftagsr=c("","title","","chapter","","codesec","sourcenote")


htags=c("","title","","chapter","","sectionnum","","sectiontitle","","codesec","","sourcenote")
htags13=c("","title","","chapter","","subchapter","","sectionnum","","sectiontitle","","codesec","","sourcenote")
```



```{r setup-xml-matter}
require(xml2)
raw.rsa=data.frame(rsaxml=character(),
                   titlenum=character(),
                   titletitle=character(),
                   chapternum=character(),
                   chaptertitle=character(),
                   subchapter=character(),
                   sectionnum=character(),
                   sectiontitle=character(),
                   text=character(),
                   sourcenote=character(),
                   repealed=logical())
```

```{r read-xml-matter}
for (rsarec in 1:length(rsahtml)){
  rsaxml<-xml2::as_list(xml2::read_html(rsahtml[rsarec]))
  rsameta<-unlist(rsaxml$html$body)
##  metalist<-which((names(rsameta)=="meta"))
  metanames=names(rsameta)
  metalist<-which(metanames!="")
  rsameta=rsameta[metalist]
  rsameta=rsameta[rsameta!="\r\n"]
  lmeta=length(rsameta)

  if (lmeta==5555){
    for (item in metalist){
      element=rsameta[item]
      ename=attr(element[[1]],"name")
      #    print(paste(rsahtml[rsarec],ename))
      
      assign(ename,attr(element[[1]],"content") )
    }
    
    df=data.frame(rsaxml=rsahtml[rsarec],titletitle=titletitle,sectiontitle=sectiontitle,chapter=chapter,text=codesect,sourcenote=sourcenote)
    raw.rsa=rbind(raw.rsa,df)
  }
  validmeta=c(7,6,3,8,9)
  if (!(lmeta %in% validmeta)){
    print(lmeta)
    print(rsarec)
  } else {
    subchapter=""
    sectionnum=""
    sectiontitle=""
    repealed=FALSE
    if (lmeta %in% c(8,9)){
      if (lmeta==8) { names(rsameta)[metalist]=dftags8
      }
      else {
        names(rsameta)[metalist]=dftags9
      }
      try((sectionnum=rsameta$sectionnum.h31),silent=T)
      try((sectiontitle=rsameta$sectiontitle),silent=T)
      repealed=TRUE
    } 
    if (lmeta==7){
      names(rsameta)[metalist]=dftags7
      try((subchapter=rsameta$subchapter.h21),silent=T)
      try((sectionnum=rsameta$sectionnum.h31),silent=T)
      try((sectiontitle=rsameta$sectiontitle),silent=T)
    } 
    if (lmeta==6){
      names(rsameta)[metalist]=dftags
      try((sectionnum=rsameta$sectionnum.h31),silent=T)
      try((sectiontitle=rsameta$sectiontitle),silent=T)
    } 
    #repealed
    if (lmeta==3){
      names(rsameta)=dftagsr
      repealed=TRUE
    } 
    sourcenote=""
    if (length(rsameta$sourcenote)>1){
      sourcenote=rsameta$sourcenote.p2
    }
    if (length(rsameta$sourcenote)==1){
      sourcenote=rsameta$sourcenote
    }
    if (sum(rsameta %like% "repealed")==0){
    df=data.frame(rsaxml=as.character(rsahtml[rsarec]),
                  titlenum=rsameta$title.h1`,
                  titlename=rsameta$title.h1[[3]],
                  chapternum=rsameta$chapter.h2`,
                  chaptertitle=rsameta$chapter.h2[[3]],
                  subchapter=subchapter,
                  sectionnum=sectionnum,
                  sectiontitle=sectiontitle,
                  text=paste(unlist(rsameta$codesec),collapse = "\r\n"),
                  sourcenote=sourcenote
    )
    raw.rsa=rbind(raw.rsa,df)
}    
    
  }  
  #else {
  #  print(rsarec)
  #  print(metalist)
  #  }
}
####RDS(raw.rsa,file="nhrsa.rds",compress = F)
#

#require(stringr)
#raw.rsa$index=1
#rsadata<-reshape2::dcast(raw.rsa,rsaxml~name+text,value.var="index")
```

